### ISSUE TITLE
Multichannel Gas Sensor ist not working

### ISSUE THREAD

**Issue by dynamik1703** [Seeed-Studio/Wio_Link#50] opened 2017-07-14 15:59 UTC
Hello,

I'm trying to use the Multichannel Gas Sensor with the Wio.

But it's not possible for me. The test request returns: {"error": "The sensor is not connected."}

I have two Wios and already the second sensor. No combination was working.

Is there a bug?

Best wishes

**Comment by KillingJacky** [comment] 2017-07-16 03:57
When did you purchase your multichannel gas sensor? In the mean time I will check with colleague  if the sensor has been revised.

**Comment by dynamik1703** [comment] 2017-07-16 12:39
I bought it 2-3 weeks ago. It's the v1.0.

Every reguest gives the response: {"error": "The sensor is not connected."}

The only exception is the CO reguest. The response is: {"concentration_ppm":-1.0}

**Comment by KillingJacky** [comment] 2017-07-17 01:47
The sensor's firmware has been updated to version 2 which breaks the protocol. You might bought the new version. I will fix the Wio driver. Sorry for the inconvenience.

**Comment by dynamik1703** [comment] 2017-07-17 16:30
Thanks great! Can you please tell me when it is ready and what do I have to do to update it?

Best wishes

**Comment by KillingJacky** [comment] 2017-07-18 02:12
I will ping you here when it's done. What you need to do is simple, just update the firmware for your Wio via the App.

**Comment by mlilius** [comment] 2017-07-18 15:01
I have this issue as well. Thank you for addressing this.

**Comment by KillingJacky** [comment] 2017-07-19 03:28
Fixed with 75440ce35ecfbca9c79029efa1804287c7fa6662
Some notes about this sensor:
- The version 2 firmware (the gas sensor) will not respond any i2c request in the first 1 second at startup, because the LED blink pattern needs 1 second. So please read the sensor after 1 second.
- The gas sensor needs to be heated at least 1 minute to get the right reading. The reading can't be stable until the sensor's been totally warmed up.

**Comment by mlilius** [comment] 2017-07-19 12:33
Thank you. I can confirm that this works now. Thanks again.

**Comment by dynamik1703** [comment] 2017-07-20 06:33
Works for me as well! Awesome.

Thank you very much. Great service!

**Comment by KillingJacky** [comment] 2017-07-21 01:43
Pleasure. Thank you guys for reporting as well. 
Will close this, if any further questions please reopen.

**Closed as completed by KillingJacky** 2017-07-21 01:43 UTC

**Comment by GanLay20** [comment] 2019-03-06 17:40
I couldn't use Multichannel gas sensor with ESP32..There is no result in serial print ...I am using Grove expansion board especially for ESP32..Thanks...
